# Simple statements

Examples from Chapter 11 of <i>Scientific Computation for Hackers: Python and the Jupyter Shell</i>

GPL license. 

In [3]:
x=1
y=2
z=3
z/=(x+y)
print(z)

1.0


In [4]:
x=1
y=2
z=3
z=z/(x+y)
print(z)

1.0


In [6]:
a,b=10,1
print("a=",a,"b=",b)

a= 10 b= 1


In [7]:
x=a
a=b
b=x
print("a=",a,"b=",b)

a= 1 b= 10


In [8]:
a,b=10,1
print("a=",a,"b=",b)

a= 10 b= 1


In [9]:
a,b=b,a
print("a=",a,"b=",b)

a= 1 b= 10


In [10]:
x=[1,2,3,4,5]
y=x
x[3]="a"
print(x, y)

[1, 2, 3, 'a', 5] [1, 2, 3, 'a', 5]


In [11]:
x=[1,2,3,4,5]
from copy import copy
y=copy(x)
x[3]="a"
print(x, y)

[1, 2, 3, 'a', 5] [1, 2, 3, 4, 5]


In [13]:
x=[1,2,[3,4,5]]
y=copy(x)
x[2][0]=23
print(x,y)

[1, 2, [23, 4, 5]] [1, 2, [23, 4, 5]]


In [14]:
from copy import deepcopy
x=[1,2,[3,4,5]]
y=deepcopy(x)
x[2][0]=23
print(x,y)

[1, 2, [23, 4, 5]] [1, 2, [3, 4, 5]]


In [15]:
assert 7==7

In [16]:
assert 3==7

AssertionError: 

In [17]:
assert 3==7, "I said to check if 3 equals 7"

AssertionError: I said to check if 3 equals 7

In [18]:
pass

In [19]:
if 23>19:
    pass

In [21]:
x=[1,2,3]
del x[1]
print(x)

[1, 3]


In [22]:
del x

In [23]:
print(x)

NameError: name 'x' is not defined

In [26]:
for i in range(10):
    print(i,end="|")

0|1|2|3|4|5|6|7|8|9|

In [25]:
x=1;y=2;z=3;
print(x,y,z)

1 2 3


In [27]:
import numpy as np
import numpy.linalg as NLA
M=np.array([[1,2,3],[4,5,6],[7,8,9]])
P,Q,R=NLA.svd(M)

In [28]:
M

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
P,Q,R

(array([[-0.21483724,  0.88723069,  0.40824829],
        [-0.52058739,  0.24964395, -0.81649658],
        [-0.82633754, -0.38794278,  0.40824829]]),
 array([1.68481034e+01, 1.06836951e+00, 4.41842475e-16]),
 array([[-0.47967118, -0.57236779, -0.66506441],
        [-0.77669099, -0.07568647,  0.62531805],
        [-0.40824829,  0.81649658, -0.40824829]]))

In [32]:
x=7
y=10
print("x, y=",x, y)
def f(a, b):
    global x
    x = a
    y = b
    print("x, y=",x,y)
    return(x,y)
u,v=f(200, 300)
print("u, v=",u,v)
print("x, y=",x, y)

x, y= 7 10
x, y= 200 300
u, v= 200 300
x, y= 200 10


In [33]:
y = 10
z="y=y+1"
exec(z)
print(y)

11


In [34]:
for i in range(10):
    exec(z)
print(y)

21


In [35]:
x=5
eval("5+x")

10

In [36]:
y="for i in range(3): print(i,'spam')"

In [37]:
exec(y)

0 spam
1 spam
2 spam


In [39]:
from math import sqrt

In [40]:
map(sqrt, [3,4,5,6])

In [41]:
list(map(sqrt, [3,4,5,6]))

[1.7320508075688772, 2.0, 2.23606797749979, 2.449489742783178]

In [44]:
list(map(lambda x:sqrt(x), [3,4,5,6]))

[1.7320508075688772, 2.0, 2.23606797749979, 2.449489742783178]

In [ ]:
list()