# Numpy Arrays

Examples from Chapter 22 of <i>Scientific Computation for Hackers: Python and the Jupyter Shell</i>

GPL license.

In [1]:
import numpy as np
x=np.array([1,2,3])
x

array([1, 2, 3])

In [2]:
y=np.array([[1,2],[3,4]])
y

array([[1, 2],
       [3, 4]])

In [3]:
A=np.array([[1,2,3],[4,5,6]])
A.shape

(2, 3)

In [4]:
A=np.array([[1,2,3],[4,5,6]])
A.ndim

2

In [5]:
A.size

6

In [6]:
A.itemsize

8

In [7]:
A.dtype

dtype('int64')

In [8]:
def f(x):
    return(x*x)
u=np.array([5,10,25])
f(u)

array([ 25, 100, 625])

In [9]:
import numpy as np
M=[[1,2,3],[4,5,6],[7,8,9],[10,11,12]] # define as a list
A=np.array(M)
# convert to an array
A

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [10]:
M[1][2]

6

In [11]:
A[1][2]

6

In [12]:
A[1,2]

6

In [13]:
M[1,2]

TypeError: list indices must be integers or slices, not tuple

In [14]:
A[:,1]

array([ 2,  5,  8, 11])

In [15]:
A[:,2]

array([ 3,  6,  9, 12])

In [16]:
A[1]

array([4, 5, 6])